### PR TITLE
Add text from Chris's analysis

### PR DESCRIPTION
**Pull request by bemasc**

### CODE REVIEW

**Comment by bemasc** [comment]
@chris-box Please review this proposed change based on your comments.

**Comment by chris-box** [comment]
Ben,

Thanks for the suggested changes!

I personally read the -00 draft as saying that relaxed validation meant the removal of checking that the IP address is covered by SubjectAlternativeName.

However in this commit, your intent appears to be go further, to define it as the removal of all mandatory validation processes, leaving only optional ones. 

From a client's perspective, I think there is merit in validating that the upstream encrypted DNS it has just connected to is provably operated by a named entity. This information can be used in deciding when to use this DNS (always/never/somewhere in between), and in generating UI messages (e.g. "upstreamisp.com has stopped responding").

Opportunistic Privacy Profile says the client "might or might not validate the resolver". If we agree there is some merit in knowing who you are talking to, then I propose to define relaxed validation as:
* Validate the encrypted resolver's certificate is signed by a chain we trust
* But do not require the IP address to be listed in the certificate

Does that make sense? If the encrypted resolver fails validation (e.g. self-signed) then I guess some clients might be happy to proceed regardless. But I'd be more comfortable setting an expectation that upstream encrypted resolvers should always be properly signed according to the client's trust store.

**Comment by bemasc** [comment]
That's an interesting observation.  This is an Informational draft, so we aren't in the business of imposing requirements, but we should definitely talk about certificate validation and how it can be beneficial.  I've added a paragraph here discussing why it might be a good idea for clients to validate certificate chains, which connects nicely with some of the mitigations later on.

Please review.

**Comment by chris-box** [comment]
Agree in principle with the extra paragraph and links to the mitigations. It is objectively correct.

However when reading it with an implementer's eye, I am concerned they will be put off by "conveys minimal security benefit on its own". The tone suggests disapproval and the subsequent words are not sufficient to remove this sense.

How about removing those words? The resulting paragraph strikes a better tone and still conveys the right information (IMHO):

`The Opportunistic Privacy Profile is a broad category, including clients that "might or might not validate" the TLS certificate chain.  Certificate validation without an authentication identity can be valuable in conjunction with a reputation system or a user approval step (see {{reputation}} and {{user-controls}}).`

**Comment by bemasc** [comment]
OK, I've removed those words and rearranged the words a bit.

**Comment by chris-box** [comment]
Looks even better, thanks. I do also want to comment on the second half of the first commit but I'll do that tomorrow.

**Comment by chris-box** [comment]
In section 4 I would like to change a couple of areas. I'm not sure if I can submit a pull request into a pull request, so instead I'll set out my proposed wording here.

```
# Naturally compatible behaviors

The following network behaviors are naturally compatible with relaxed validation. The first
three are concerned with cases where they are implemented on the Legacy DNS Forwarder, with
the final one considering the upstream resolver.
```

```
## Upstream resolver services

The forwarder's upstream resolver might provide additional services, such as filtering.
These services are generally independent of cross-forwarder upgrade, and hence naturally
compatible.

In special cases where the upstream resolver requires cooperation from a legacy forwarder
(e.g. for marking certain queries), one solution is for the upstream resolver to choose
not to deploy DDR until all cooperating forwarders have been upgraded. Alternatively,
each legacy forwarder can block "resolver.arpa" as described above.
```

The first one of these seeks to clarify that the network behaviours discussed here are mostly forwarder behaviours.

The second one removes query logging (because I think it is rare), states things in a different way, and notes an alternative solution to the last problem.

**Comment by bemasc** [comment]
OK, I've incorporated your text on upstream services.  Instead of discussing the different scopes in text, I've split this section into "local" and "upstream" subsections.

**Comment by chris-box** [comment]
That works for me!

**Comment by chris-box** [comment]
That works for me!

**Pull request merged**
